language: node_js
node_js:
  - "7"
before_script:
  - npm install gulp -g
  - npm install hexo-cli -g
  - git clone https://github.com/viosey/hexo-theme-material.git
  - cd hexo-theme-material
  - git checkout -t origin/canary
  - git pull
  - rm -rf .git
  - cd ..
  - cp -R hexo-theme-material/ _hexo/themes/material
install:
  - cd ./_hexo
  - npm install
script:
  - chmod +x ../build.sh
  - chmod +x ../deploy.sh
  - ../build.sh > /dev/null
  - ../deploy.sh > /dev/null
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"