language: node_js
node_js:
  - "7"
install:
  - npm install gulp -g
  - npm install hexo-cli -g
before_script:
  - cd _hexo
  - chmod +x ../install-material.sh
  - chmod +x ../build.sh
  - chmod +x ../deploy.sh
  - chmod +x ../deploy.sh
  - ../install-material.sh > /dev/null
script:
  - ../build.sh > /dev/null
  - ../deploy.sh > /dev/null
  - ../test.sh > /dev/null
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
