language: node_js
node_js:
  - "7"
before_script:
  - npm install gulp -g
  - npm install hexo-cli -g
  - cd _hexo
  - npm install
  - git clone https://github.com/viosey/hexo-theme-material.git themes/material
  - cd themes/material
  - git checkout -t origin/canary
  - git pull
  - rm -rf .git
  - cd ..
  - cd ..
  - cp -i ./_config.theme.yml themes/material/_config.yml
script:
  - chmod +x ../build.sh
  - chmod +x ../deploy.sh
  - ../build.sh > /dev/null
  - ../deploy.sh > /dev/null
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"